name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./  # So paths are relative from root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install frontend dependencies
        run: npm install
        working-directory: client

      - name: Build frontend
        run: npm run build
        working-directory: client

      - name: Install backend dependencies
        run: npm install
        working-directory: server
